# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_test:
    docker:
      - image: circleci/python:2.7.14

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
      - run:
          name: checkout result 
          command: |
            ls -lrt .
            pwd
            python -c "import wx;print(wx.version())"
      - run:
          name: Unit Test
          command: | 
            pwd
            python -m unittest discover -vf tests

#  test:
#    docker:
#      - image: circleci/python:2.7.14
#    steps:
#      - checkout

    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test
#      - test
